<?php

namespace Database\Seeders;

use App\Models\DynamicPage;
use Illuminate\Database\Seeder;

class DynamicPageSeoContentSeeder extends Seeder
{
    public function run(): void
    {
        $pages = $this->getPageContent();

        foreach ($pages as $slug => $data) {
            $page = DynamicPage::where('slug', $slug)->first();
            if ($page) {
                $page->update([
                    'city_specific_content' => $data['city_specific_content'],
                    'seo_content' => $data['seo_content'],
                    'faqs' => $data['faqs'],
                ]);
            }
        }
    }

    private function getPageContent(): array
    {
        return [
            // =====================================================
            // EUROPE B2B DMC PAGES
            // =====================================================

            'europe-b2b-dmc-in-chennai' => [
                'city_specific_content' => "Chennai, the gateway to South India, has seen a remarkable surge in outbound travel demand over the past few years. Travel agents in Chennai are increasingly looking for reliable B2B DMC partners who can offer curated European tour packages at competitive wholesale rates. GYF Holidays has been serving the Chennai travel trade since our inception, building strong relationships with agencies across T. Nagar, Anna Nagar, Adyar, and other key business districts.\n\nWith direct flight connectivity from Chennai International Airport to major European hubs like London, Paris, and Frankfurt, your clients from Chennai can easily access our extensive European tour network. We understand that Chennai's clientele values cultural experiences, historical tours, and family-friendly European packages, which is why our itineraries are designed to cater to these specific preferences.\n\nOur dedicated Chennai support team ensures that travel agents receive prompt quotations, real-time availability updates, and personalized itinerary modifications. Whether your clients are honeymooners looking for romantic European getaways or corporate groups planning incentive trips, GYF Holidays provides end-to-end DMC support with transparent B2B pricing.",
                'seo_content' => "As a leading Europe B2B DMC serving Chennai travel agents, GYF Holidays covers all major European destinations including France, Italy, Switzerland, Spain, Germany, Netherlands, Austria, Czech Republic, Hungary, and more. Our packages range from budget-friendly group tours to luxury customized European experiences.\n\nChennai-based travel agents benefit from our special seasonal offers on popular European routes, early booking discounts, and flexible payment terms designed specifically for the B2B trade. Our portfolio includes over 50 pre-designed European itineraries that can be customized based on your client requirements, group size, and budget.\n\nWe also provide comprehensive visa documentation support for Schengen visa applications, ensuring your Chennai clients have a hassle-free travel experience from start to finish.",
                'faqs' => [
                    ['question' => 'What European destinations does GYF Holidays cover for Chennai travel agents?', 'answer' => 'GYF Holidays covers all major European destinations including France, Italy, Switzerland, Spain, Germany, Netherlands, Austria, Czech Republic, Hungary, Greece, Croatia, Portugal, and the Nordic countries. We offer over 50 pre-designed itineraries that can be customized for Chennai-based travel agents.'],
                    ['question' => 'How can travel agents in Chennai partner with GYF Holidays?', 'answer' => 'Chennai travel agents can partner with us by submitting an enquiry through our website or contacting our sales team directly. We offer competitive B2B commission structures, dedicated account managers, and training sessions for your team on our European products.'],
                    ['question' => 'What is the B2B pricing model for Europe packages from Chennai?', 'answer' => 'We offer wholesale net rates to registered B2B partners. Travel agents in Chennai can add their own markup to our base prices. We provide transparent pricing with no hidden costs, and special group rates for bookings of 15 or more passengers.'],
                    ['question' => 'Does GYF Holidays help with Schengen visa processing for Chennai clients?', 'answer' => 'Yes, we provide complete Schengen visa documentation support including invitation letters, hotel confirmations, detailed itineraries, and travel insurance. Our team guides Chennai travel agents through the entire visa application process for their clients.'],
                    ['question' => 'What support does GYF provide during European tours booked from Chennai?', 'answer' => 'We provide 24/7 on-ground support across Europe, including airport transfers, English-speaking guides, emergency assistance, and real-time communication with the Chennai travel agent throughout the tour duration.'],
                    ['question' => 'What are the most popular European packages for Chennai tourists?', 'answer' => 'The most popular packages from Chennai include the Classic Europe tour covering Paris, Switzerland, and Italy, London-Paris combination, Scandinavia Northern Lights tour, and the Mediterranean cruise packages covering Greece, Croatia, and Italy.'],
                ],
            ],

            'europe-b2b-dmc-in-delhi' => [
                'city_specific_content' => "Delhi, as the capital of India and its largest travel hub, represents our most significant B2B market. Travel agents across Delhi NCR - from Connaught Place to Dwarka, Karol Bagh to Rajouri Garden - rely on GYF Holidays for premium European tour packages at the best B2B rates. Our head office is located in Dwarka, Delhi, giving local agents the advantage of face-to-face meetings, product training sessions, and instant support.\n\nDelhi's Indira Gandhi International Airport offers the widest range of direct European connections in India, with non-stop flights to London, Paris, Frankfurt, Amsterdam, Rome, and many more destinations. This connectivity makes Delhi the ideal departure point for European tours, and our packages are optimized to take advantage of these direct routes.\n\nDelhi's diverse clientele - from high-net-worth individuals seeking luxury European experiences to budget-conscious family groups and corporate MICE delegations - demands a versatile DMC partner. GYF Holidays offers tiered packages across all budget segments, ensuring Delhi travel agents can serve every type of client with confidence.",
                'seo_content' => "As a Delhi-based Europe B2B DMC, GYF Holidays offers unparalleled advantages to local travel agents. Our proximity means faster communication, in-person product demos, and the ability to attend our regular training workshops at our Dwarka office. We organize monthly familiarization trips for Delhi travel agents to experience our European products firsthand.\n\nDelhi travel agents enjoy priority access to our limited-availability packages, early-bird pricing on peak season departures, and flexible cancellation policies designed for the competitive Delhi market. Our dedicated Delhi sales team of experienced professionals understands the unique demands of the NCR travel trade.\n\nWe also support Delhi agents with co-branded marketing materials, social media content, and point-of-sale displays to help them promote European tours to their walk-in customers effectively.",
                'faqs' => [
                    ['question' => 'Where is GYF Holidays office located in Delhi?', 'answer' => 'Our head office is located at Unit No 590, 5th Floor, Vegas Commercial Building, Plot No 6, Block B, Sector 14, Dwarka, New Delhi 110078. Delhi travel agents are welcome to visit us for product discussions and training sessions.'],
                    ['question' => 'What makes GYF Holidays the best Europe B2B DMC in Delhi?', 'answer' => 'As a Delhi-based company, we offer local presence, face-to-face support, regular product training workshops, competitive B2B rates with the widest European destination coverage, and 24/7 on-ground support. Our 10+ years of experience and 5000+ happy clients speak for our reliability.'],
                    ['question' => 'How quickly can Delhi agents get a quotation for Europe packages?', 'answer' => 'Delhi travel agents typically receive quotations within 2-4 hours during business hours. For urgent requirements, our in-office team can provide instant quotes. We also offer a quick-quote tool for registered B2B partners on our portal.'],
                    ['question' => 'Does GYF offer MICE packages for Delhi corporates to Europe?', 'answer' => 'Yes, we specialize in MICE packages to Europe for Delhi-based corporates. We handle everything from venue selection and conference arrangements to team-building activities and gala dinners across European destinations.'],
                    ['question' => 'What payment terms does GYF offer to Delhi travel agents?', 'answer' => 'We offer flexible payment terms including advance booking with partial payment, credit facilities for established partners, and multiple payment modes including bank transfer, cheques, and online payments. Terms vary based on partnership duration and volume.'],
                    ['question' => 'Can GYF customize Europe packages for specific Delhi client requirements?', 'answer' => 'Absolutely. Every package can be fully customized from hotel categories and meal plans to specific activity inclusions and routing. Our expert team creates bespoke itineraries based on your Delhi client preferences, group size, and budget.'],
                ],
            ],

            'europe-b2b-dmc-in-mumbai' => [
                'city_specific_content' => "Mumbai, India's financial capital and a major hub for outbound travel, is a key market for GYF Holidays B2B DMC services. Travel agents across Mumbai - from Fort and Colaba to Andheri, Borivali, and Thane - trust us for reliable European tour packages that meet the expectations of Mumbai's discerning travellers.\n\nMumbai's Chhatrapati Shivaji Maharaj International Airport offers excellent European connectivity with direct flights to London, Paris, Frankfurt, Amsterdam, and more. The city's affluent clientele, including corporate executives and HNI families, often seek premium European experiences from Swiss Alpine retreats to Mediterranean yacht cruises.\n\nGYF Holidays understands that Mumbai travel agents operate in a fast-paced, competitive environment. That's why we offer instant quotations, real-time availability checks, and a dedicated Mumbai relationship manager who understands the local market dynamics and client expectations.",
                'seo_content' => "Mumbai travel agents partnering with GYF Holidays gain access to exclusive European packages designed for the premium Mumbai market. Our luxury European collection includes private villa stays in Tuscany, exclusive wine tours in France, premium Northern Lights experiences in Scandinavia, and VIP city breaks in London and Paris.\n\nFor the budget-conscious segment, we offer value-packed group tours covering 5-7 European countries at competitive B2B rates. Mumbai agents can choose from our ready-made packages or request fully customized itineraries based on their client briefs.\n\nWe regularly conduct product presentations and educational seminars for Mumbai travel agents at premium hotels across the city, ensuring our partners stay updated on the latest European travel trends and our newest product offerings.",
                'faqs' => [
                    ['question' => 'What European tour packages are most popular with Mumbai travellers?', 'answer' => 'Mumbai travellers prefer luxury European experiences including Swiss-Paris-London combination tours, Mediterranean cruises, Italian honeymoon packages, and exclusive Northern Lights trips to Scandinavia. We also see strong demand for short city breaks to London and Paris.'],
                    ['question' => 'How do Mumbai travel agents register with GYF Holidays?', 'answer' => 'Mumbai agents can register by contacting our sales team or filling out the enquiry form on our website. We require basic business documentation and offer a quick onboarding process with immediate access to our B2B rates and booking system.'],
                    ['question' => 'Does GYF offer luxury European packages for Mumbai HNI clients?', 'answer' => 'Yes, we specialize in luxury European experiences for Mumbai HNI clients including private transfers, 5-star hotels, Michelin-star dining, private guided tours, helicopter rides, and exclusive VIP experiences across Europe.'],
                    ['question' => 'What commission structure does GYF offer Mumbai travel agents?', 'answer' => 'We offer competitive net rates that allow Mumbai agents to set their own markups. Higher volume partners qualify for additional incentives, override commissions, and exclusive deals. Contact our Mumbai relationship manager for detailed partnership terms.'],
                    ['question' => 'Can GYF arrange European corporate retreats for Mumbai companies?', 'answer' => 'Absolutely. We have extensive experience organizing corporate retreats, team-building trips, and incentive tours to Europe for Mumbai-based companies. We handle end-to-end logistics including conference venues, team activities, and gala dinners.'],
                ],
            ],

            'europe-b2b-dmc-in-bangalore' => [
                'city_specific_content' => "Bangalore, India's Silicon Valley and IT capital, generates significant outbound European travel demand, particularly from the tech industry. Travel agents in Bangalore serving IT companies, startups, and tech professionals find GYF Holidays to be the ideal B2B DMC partner for European tour packages.\n\nBangalore's tech-savvy clientele often looks for unique European experiences beyond the standard tourist circuit. GYF Holidays creates innovative itineraries that appeal to this forward-thinking demographic, combining cultural exploration with modern European experiences.\n\nWith Kempegowda International Airport expanding its European route network, Bangalore travellers now have more direct and convenient connections to European destinations. Our packages are designed to optimize these new routes, offering better pricing and shorter travel times for Bangalore departures.",
                'seo_content' => "Bangalore travel agents benefit from GYF Holidays tech-forward approach to B2B travel services. We offer a digital-first booking experience with online quotation tools, real-time availability tracking, and automated documentation - features that resonate with Bangalore's tech-savvy travel trade.\n\nThe IT corridor in Bangalore generates massive demand for European incentive travel. Companies in Electronic City, Whitefield, and Manyata Tech Park regularly send teams on European reward trips. GYF Holidays has the expertise to handle large group movements across Europe seamlessly.\n\nWe also cater to Bangalore's growing luxury honeymoon market with romantic European packages covering Santorini, Swiss Alps, Paris, Venice, and the Amalfi Coast at competitive B2B rates for Bangalore travel agents.",
                'faqs' => [
                    ['question' => 'Why do Bangalore IT companies choose GYF for European incentive trips?', 'answer' => 'Bangalore IT companies choose GYF Holidays because we specialize in handling large group movements across Europe, offer competitive corporate rates, provide dedicated MICE coordinators, and have proven experience organizing tech company incentive trips including team activities and conference arrangements.'],
                    ['question' => 'What European packages are trending among Bangalore travellers?', 'answer' => 'Trending packages from Bangalore include Scandinavian Northern Lights tours, Switzerland-Italy honeymoon packages, London city tours, Eastern Europe budget tours covering Prague, Budapest, and Vienna, and Mediterranean summer cruises.'],
                    ['question' => 'Does GYF Holidays offer customized European corporate tours from Bangalore?', 'answer' => 'Yes, we create fully customized corporate tours including tech hub visits in European cities, team-building activities in the Alps, corporate conferences in historic venues, and innovation tours covering startups and tech ecosystems in Berlin, Amsterdam, and Stockholm.'],
                    ['question' => 'How can Bangalore travel agents access GYF Holidays B2B portal?', 'answer' => 'Bangalore agents can request B2B portal access by registering through our website. The portal provides instant quotations, real-time availability, booking management, and downloadable marketing materials for European tour packages.'],
                    ['question' => 'What is the lead time for booking Europe packages from Bangalore?', 'answer' => 'We recommend a minimum 45-60 days lead time for standard European packages and 90 days for peak season from June to September. However, we can accommodate last-minute requests based on availability. Bangalore agents receive priority processing for urgent bookings.'],
                ],
            ],

            'europe-b2b-dmc-in-kolkata' => [
                'city_specific_content' => "Kolkata, the cultural capital of India, has a growing community of travel agents who are expanding their European tour offerings. GYF Holidays serves as a trusted B2B DMC partner for Kolkata travel agents, providing them access to comprehensive European tour packages that appeal to Kolkata's culturally inclined travellers.\n\nKolkata's clientele has a deep appreciation for art, history, architecture, and culinary experiences making European destinations with rich cultural heritage particularly popular. Our European itineraries for Kolkata agents emphasize museum visits, heritage walks, local culinary experiences, and art gallery tours alongside standard sightseeing.\n\nNetaji Subhas Chandra Bose International Airport is expanding its international connectivity, making European travel more accessible for Kolkata residents. GYF Holidays packages are optimized for the best connections via major Gulf and European hub airports.",
                'seo_content' => "Kolkata travel agents partnering with GYF Holidays can offer their clients culturally enriched European experiences that go beyond standard tourism. Our Heritage Europe collection includes guided tours of the Louvre, Vatican Museums, British Museum, and Uffizi Gallery which resonate deeply with Kolkata's art-loving travellers.\n\nWe understand that Kolkata's travel market is price-sensitive, which is why we offer specially curated budget-friendly European packages without compromising on quality. Our value packages cover essential European highlights with comfortable 3-4 star accommodation and quality ground services.\n\nGYF Holidays also supports Kolkata agents with festival-season promotions aligned with Durga Puja, Diwali, and other key booking periods in the Kolkata market.",
                'faqs' => [
                    ['question' => 'What European packages are popular among Kolkata travellers?', 'answer' => 'Kolkata travellers favour culturally rich European packages including the Classic Europe circuit covering Paris, Switzerland, and Italy, UK heritage tours, Eastern Europe budget tours through Prague, Budapest, and Vienna, and Mediterranean cultural cruises.'],
                    ['question' => 'Does GYF offer budget-friendly Europe packages for Kolkata agents?', 'answer' => 'Yes, we offer specially curated budget-friendly European packages at competitive per-person rates. These value packages include comfortable 3-star hotels, essential sightseeing, and quality ground services ideal for the price-conscious Kolkata market.'],
                    ['question' => 'How does GYF Holidays support Kolkata travel agents?', 'answer' => 'We provide dedicated support including quick quotation turnaround, Schengen visa documentation assistance, marketing materials, training webinars, and a dedicated relationship manager. Kolkata agents also benefit from our flexible payment terms and competitive B2B rates.'],
                    ['question' => 'What is the best time to book Europe tours from Kolkata?', 'answer' => 'The peak travel season for Kolkata to Europe is April to September. We recommend booking 60-90 days in advance for the best rates and availability. However, we offer year-round packages including winter European experiences and Christmas market tours.'],
                    ['question' => 'Can GYF arrange group tours from Kolkata to Europe?', 'answer' => 'Absolutely. We specialize in group tours from Kolkata ranging from small family groups to large 50+ person delegations. Group tours include special B2B rates, dedicated tour managers, and customized itineraries based on group preferences.'],
                ],
            ],

            'europe-b2b-dmc-in-hyderabad' => [
                'city_specific_content' => "Hyderabad, with its booming IT sector and growing affluence, has emerged as one of India's fastest-growing outbound travel markets. Travel agents in Hyderabad from Banjara Hills to HITEC City, Jubilee Hills to Gachibowli are increasingly looking for dependable B2B DMC partners for European tour packages.\n\nHyderabad's pharma and IT industries drive significant corporate travel demand to Europe, with companies regularly organizing incentive trips, conference delegations, and business development tours to European cities. GYF Holidays provides comprehensive MICE and leisure European packages tailored to Hyderabad's corporate and family travel segments.\n\nRajiv Gandhi International Airport's expanding international network makes European travel increasingly convenient for Hyderabad residents. Our packages leverage the best routing options to offer competitive pricing for Hyderabad departures.",
                'seo_content' => "Hyderabad travel agents partnering with GYF Holidays access a comprehensive European DMC network covering 20+ countries. Our Hyderabad-specific offerings include pharma industry conference support packages to European cities, IT company incentive tours, and premium family European vacations.\n\nThe Hyderabad market shows strong growth in honeymoon travel to Europe, particularly to Switzerland, Paris, and Santorini. GYF Holidays offers exclusive honeymoon packages with romantic add-ons, private transfers, and premium hotel upgrades at competitive B2B rates.\n\nWe conduct regular product familiarization sessions for Hyderabad travel agents, covering our latest European offerings, seasonal promotions, and booking procedures.",
                'faqs' => [
                    ['question' => 'What European destinations are most requested by Hyderabad clients?', 'answer' => 'Hyderabad clients frequently request Switzerland, France, Italy, UK, Netherlands, and Scandinavian countries. There is also growing interest in Eastern Europe and Mediterranean destinations among Hyderabad travellers.'],
                    ['question' => 'Does GYF handle European conference travel for Hyderabad pharma companies?', 'answer' => 'Yes, we have extensive experience arranging European conference and business travel for Hyderabad pharma and IT companies. This includes event registration coordination, hotel blocks near conference venues, local transfers, and optional post-conference leisure extensions.'],
                    ['question' => 'What B2B commission does GYF offer Hyderabad travel agents?', 'answer' => 'We provide competitive net rates allowing Hyderabad agents to determine their own markup. Volume-based incentive programs, seasonal bonuses, and performance rewards are available for committed B2B partners.'],
                    ['question' => 'How fast can GYF deliver Europe tour quotations for Hyderabad agents?', 'answer' => 'Standard quotations are delivered within 4-6 hours during business hours. Express quotations for urgent requirements can be arranged within 2 hours. Our digital quotation system ensures accuracy and speed for Hyderabad travel agents.'],
                    ['question' => 'Does GYF offer honeymoon Europe packages for Hyderabad couples?', 'answer' => 'Yes, we offer curated honeymoon packages to romantic European destinations including Paris, Venice, Santorini, Swiss Alps, and Amalfi Coast. Packages include private transfers, premium hotels, candlelight dinners, and surprise romantic setups.'],
                ],
            ],

            // =====================================================
            // SCANDINAVIA B2B DMC PAGES
            // =====================================================

            'scandinavia-b2b-dmc-in-chennai' => [
                'city_specific_content' => "Scandinavian destinations have seen a massive surge in popularity among Chennai travellers, particularly for Northern Lights experiences, midnight sun adventures, and Nordic cultural tours. As a specialist Scandinavia B2B DMC, GYF Holidays helps Chennai travel agents tap into this growing demand with expertly crafted Nordic tour packages.\n\nChennai clients are increasingly moving beyond traditional European destinations and exploring the unique offerings of Norway, Sweden, Finland, Denmark, and Iceland. From chasing the Aurora Borealis in Tromso to experiencing the Finnish Lapland, our Scandinavian packages offer Chennai travellers something truly extraordinary.\n\nGYF Holidays provides Chennai agents with comprehensive Scandinavian expertise including destination knowledge, visa guidance for Nordic countries, and seasonal recommendations to help clients choose the perfect time for their Nordic adventure.",
                'seo_content' => "Our Scandinavia packages for Chennai travel agents cover the full spectrum of Nordic experiences from budget-friendly Nordic capital city tours to premium Northern Lights expeditions and luxury Arctic cruise packages.\n\nPopular Scandinavian itineraries from Chennai include the Classic Nordic Capitals tour covering Copenhagen, Stockholm, Oslo, and Helsinki, Finnish Lapland Northern Lights adventure, Norway Fjords expedition, Iceland Golden Circle tour, and the combined Scandinavia-Northern Lights package.\n\nWe also offer seasonal special packages including Christmas in Lapland, Midnight Sun summer tours, and Arctic wildlife expeditions that help Chennai agents differentiate their offerings in a competitive market.",
                'faqs' => [
                    ['question' => 'What Scandinavian countries does GYF Holidays cover for Chennai agents?', 'answer' => 'We cover all five Nordic countries including Norway, Sweden, Finland, Denmark, and Iceland. Our packages include capital city tours, Northern Lights expeditions, fjord cruises, Lapland adventures, and Arctic Circle experiences.'],
                    ['question' => 'When is the best time to see the Northern Lights from Chennai?', 'answer' => 'The Northern Lights season runs from September to March, with peak visibility in November to February. We recommend Chennai clients plan their Nordic trip during this window for the best Aurora Borealis experience.'],
                    ['question' => 'Are Scandinavian tours expensive compared to standard European tours?', 'answer' => 'Scandinavian tours are typically priced higher than standard European tours due to the higher cost of living in Nordic countries. However, GYF Holidays offers competitive B2B rates that allow Chennai agents to provide value-driven Scandinavian packages across different budget segments.'],
                    ['question' => 'Does GYF offer Lapland Christmas packages for Chennai families?', 'answer' => 'Yes, our Lapland Christmas packages are among our most popular offerings. These include visits to Santa Claus Village, reindeer sleigh rides, snowmobile safaris, ice hotel stays, and Northern Lights viewing.'],
                    ['question' => 'What visa is required for Scandinavian countries from Chennai?', 'answer' => 'Chennai clients need a Schengen visa for Norway, Sweden, Finland, and Denmark. Iceland also falls under the Schengen agreement. GYF Holidays provides complete visa documentation support for all Nordic country applications through the Chennai VFS centers.'],
                ],
            ],

            'scandinavia-b2b-dmc-in-delhi' => [
                'city_specific_content' => "Delhi's travel market shows rapidly growing interest in Scandinavian destinations, driven by social media trends around Northern Lights, Nordic design, and Arctic adventures. GYF Holidays, headquartered in Delhi, offers local travel agents the best access to comprehensive Scandinavian B2B DMC services.\n\nDelhi clients benefit from relatively convenient air connections to Scandinavian capitals through major European hubs. Our packages are routed through the most efficient connections from Delhi's IGI Airport, minimizing travel time and maximizing the Nordic experience.\n\nAs a Delhi-based company, we offer in-person training sessions on our Scandinavian products, helping Delhi agents become Nordic travel experts. Our product team regularly updates agents on new experiences, seasonal availability, and trending Nordic destinations.",
                'seo_content' => "Delhi travel agents choosing GYF Holidays for Scandinavia packages get the advantage of our local presence, instant support, and deep Nordic destination expertise. We cover the full range of Scandinavian experiences from budget Nordic capital tours to ultra-luxury Arctic expeditions.\n\nOur Delhi office hosts monthly Scandinavia product sessions where agents can learn about Nordic destinations, seasonal highlights, and selling tips. We also organize annual familiarization trips to Scandinavian countries for top-performing Delhi B2B partners.\n\nPopular Scandinavia packages from Delhi include the 7-night Nordic Capitals tour, 5-night Northern Lights Finland experience, 10-night Norway Fjords and Northern Lights tour, and the 8-night Iceland Complete package.",
                'faqs' => [
                    ['question' => 'What Scandinavia packages does GYF offer for Delhi travel agents?', 'answer' => 'We offer a comprehensive range including Nordic Capital city tours, Finland Northern Lights expeditions, Norway Fjords cruises, Iceland Golden Circle, Swedish Lapland adventures, and combination packages at competitive B2B rates for Delhi agents.'],
                    ['question' => 'Can Delhi agents visit GYF office for Scandinavia product training?', 'answer' => 'Yes, our Dwarka office in Delhi hosts regular product training sessions on Scandinavian destinations. Delhi agents can schedule one-on-one meetings with our Nordic specialists or attend our monthly group training sessions.'],
                    ['question' => 'What is the best routing from Delhi to Scandinavia?', 'answer' => 'The most efficient routes from Delhi to Scandinavian capitals are via Helsinki with Finnair, Copenhagen via European hubs, Stockholm via Amsterdam or Frankfurt, and Oslo via London or Amsterdam. We optimize routing for the best fares and shortest travel times.'],
                    ['question' => 'Does GYF offer group discounts for Scandinavia tours from Delhi?', 'answer' => 'Yes, we offer progressive group discounts starting from 10+ passengers. Larger groups of 20+ receive additional benefits including complimentary tour leader, upgraded hotels, and exclusive group activities.'],
                    ['question' => 'Are there budget Scandinavia options for Delhi price-sensitive clients?', 'answer' => 'Absolutely. We offer value Scandinavia packages focusing on Nordic capitals with 3-star accommodations and essential experiences. These budget-friendly options allow Delhi agents to introduce clients to Scandinavia without the premium price tag.'],
                ],
            ],

            'scandinavia-b2b-dmc-in-mumbai' => [
                'city_specific_content' => "Mumbai's affluent and well-travelled clientele has developed a strong appetite for unique Scandinavian experiences. From Northern Lights honeymoon packages to luxury Arctic cruises and designer shopping tours in Copenhagen, GYF Holidays helps Mumbai travel agents offer premium Nordic packages that match their clients' sophisticated expectations.\n\nMumbai travellers are among the early adopters of emerging destinations, and Scandinavia fits perfectly into this trend. Our packages for the Mumbai market emphasize exclusive experiences like private Northern Lights viewing in glass igloos, luxury fjord cruises, and exclusive access to Arctic wildlife encounters.\n\nGYF Holidays provides Mumbai agents with marketing support including high-quality visual content of Scandinavian destinations, social media assets, and presentation materials to help showcase Nordic tours to their premium Mumbai clientele.",
                'seo_content' => "Mumbai agents choosing GYF Holidays for Scandinavian B2B packages benefit from our extensive Nordic network of hand-picked hotels, experienced English-speaking guides, and exclusive local experiences that set our packages apart from standard offerings.\n\nOur premium Scandinavia collection for Mumbai agents includes Glass Igloo Northern Lights in Finland, Norwegian Fjord luxury cruise, Iceland Blue Lagoon and Golden Circle, Swedish Icehotel experience, and Greenland Arctic expedition packages.\n\nWe also offer combination packages that pair Scandinavian destinations with other European countries such as London plus Iceland, Paris plus Norway, or Amsterdam plus Copenhagen which are popular with Mumbai clients who want to maximize their European trip.",
                'faqs' => [
                    ['question' => 'What luxury Scandinavia packages does GYF offer for Mumbai clients?', 'answer' => 'Our luxury Scandinavian collection includes Glass Igloo stays in Finland, Norwegian Fjord private cruises, Iceland exclusive Blue Lagoon packages, Swedish Icehotel experiences, and Greenland Arctic expeditions at competitive B2B rates for Mumbai agents.'],
                    ['question' => 'Are Scandinavia honeymoon packages available for Mumbai couples?', 'answer' => 'Yes, we offer romantic Scandinavian honeymoon packages featuring Northern Lights viewing, cozy Finnish cabin stays, Norwegian fjord cruises, Reykjavik city breaks, and Swedish countryside retreats with special romantic arrangements.'],
                    ['question' => 'What is the ideal duration for a Scandinavia tour from Mumbai?', 'answer' => 'We recommend 7-10 nights for a comprehensive Scandinavian experience. A 7-night package covers 2-3 countries comfortably, while 10-12 nights allows deeper exploration including Arctic Circle destinations.'],
                    ['question' => 'Does GYF combine Scandinavia with other European destinations?', 'answer' => 'Yes, combination packages are very popular with Mumbai clients. Popular combos include London plus Iceland, Paris plus Norway, Amsterdam plus Copenhagen, and a full Nordic plus Western Europe circuit.'],
                    ['question' => 'How does GYF handle extreme weather concerns for Mumbai clients in Scandinavia?', 'answer' => 'We provide detailed weather briefings and packing guides for every season. Our itineraries account for daylight hours and weather conditions, and we include appropriate indoor alternatives. All clients receive emergency weather protocols and 24/7 on-ground support.'],
                ],
            ],

            'scandinavia-b2b-dmc-in-bangalore' => [
                'city_specific_content' => "Bangalore's tech-savvy travellers have a natural affinity for Scandinavian destinations, drawn by the Nordic region's innovation culture, sustainable design, and pristine natural landscapes. Travel agents in Bangalore find GYF Holidays to be the ideal B2B partner for Scandinavian tours, especially for tech company groups and young professional travellers.\n\nThe Nordic countries' reputation for technology, design, and quality of life resonates strongly with Bangalore's IT community. Our specialized packages include Nordic tech city tours, sustainable tourism experiences, and design-focused itineraries alongside the classic Northern Lights and fjord experiences.\n\nBangalore's growing number of direct and efficient connections to European hubs makes Scandinavian travel increasingly accessible. GYF Holidays optimizes routing and pricing specifically for Bangalore departures.",
                'seo_content' => "GYF Holidays offers Bangalore travel agents a diverse range of Scandinavian packages that appeal to the city's unique demographic mix including tech professionals seeking Nordic innovation tours, young couples looking for Northern Lights honeymoon packages, and families wanting safe and culturally rich Scandinavian holidays.\n\nOur Nordic Tech and Innovation tour is particularly popular with Bangalore IT companies, covering startup hubs in Stockholm, Helsinki, and Copenhagen with meetings at tech companies, co-working spaces, and innovation centers.\n\nFor leisure travellers from Bangalore, our best-selling packages include the 7-night Finland Northern Lights and Lapland Adventure, 8-night Norway Fjords and Bergen Explorer, and the 10-night Complete Scandinavia covering all four Nordic capitals.",
                'faqs' => [
                    ['question' => 'Why is Scandinavia popular with Bangalore tech professionals?', 'answer' => 'Scandinavia appeals to Bangalore tech professionals due to its world-leading innovation ecosystem, sustainable technology initiatives, and high quality of life. Many Bangalore IT companies choose Nordic destinations for incentive trips, combining tech hub visits with natural experiences.'],
                    ['question' => 'Does GYF offer Nordic tech and innovation tours for Bangalore companies?', 'answer' => 'Yes, our Nordic Innovation Tour covers tech hubs in Stockholm, Helsinki, and Copenhagen. Tours include visits to co-working spaces, startup meetups, and tech company office tours alongside cultural experiences.'],
                    ['question' => 'What is the best Scandinavia package for Bangalore honeymooners?', 'answer' => 'Our most popular honeymoon package is the 8-night Finland and Norway Northern Lights Romance tour, featuring glass igloo stays, private Aurora viewing, cozy cabin retreats, and fjord sunset cruises.'],
                    ['question' => 'Are summer Scandinavia tours available from Bangalore?', 'answer' => 'Yes, summer from June to August is a wonderful time to visit Scandinavia for midnight sun experiences, fjord cruises, hiking, and outdoor adventures. Summer packages are popular with Bangalore families.'],
                    ['question' => 'What Scandinavia B2B rates does GYF offer Bangalore agents?', 'answer' => 'We provide competitive net rates on all Scandinavian packages with flexible markup options. Bangalore agents receive seasonal promotional rates, early booking discounts, and group pricing benefits.'],
                ],
            ],

            'scandinavia-b2b-dmc-in-kolkata' => [
                'city_specific_content' => "Kolkata's well-read and culturally curious travellers are discovering the enchanting world of Scandinavian destinations. GYF Holidays helps Kolkata travel agents introduce their clients to the magic of Nordic countries from the literary heritage of Copenhagen to the artistic traditions of Stockholm and the folklore of Finnish Lapland.\n\nKolkata's appreciation for art, literature, and cultural heritage makes Scandinavian destinations a natural fit. Our Nordic packages for the Kolkata market emphasize cultural immersion, museum visits, local traditions, and authentic Nordic experiences alongside natural wonders like Northern Lights and fjords.\n\nGYF Holidays understands Kolkata's price-sensitive market and offers tiered Scandinavian packages across budget segments, ensuring every Kolkata travel agent can provide Nordic tours to their clients regardless of budget.",
                'seo_content' => "Kolkata travel agents partnering with GYF Holidays for Scandinavian packages can offer their clients unique Nordic cultural experiences including visits to world-class museums, Scandinavian design studios, Viking heritage sites, and traditional Nordic culinary experiences.\n\nOur budget-friendly Scandinavian city breaks are ideal for introducing Kolkata clients to the Nordic world covering Copenhagen, Stockholm, or Helsinki in focused 5-night packages that deliver authentic experiences at accessible price points.\n\nWe also offer seasonal specials aligned with Kolkata's peak booking periods, including Puja season early booking offers and winter Northern Lights promotions.",
                'faqs' => [
                    ['question' => 'What budget-friendly Scandinavia options does GYF offer for Kolkata?', 'answer' => 'We offer value Scandinavian packages starting with 5-night Nordic capital city breaks, budget Northern Lights tours with cabin stays, and group packages with shared services making Nordic travel accessible for the Kolkata market.'],
                    ['question' => 'Which Scandinavian destination is best for first-time Kolkata travellers?', 'answer' => 'We recommend Copenhagen or Helsinki for first-time Nordic travellers from Kolkata. Both cities are easy to navigate, have rich cultural offerings, and serve as excellent gateways to broader Scandinavian experiences.'],
                    ['question' => 'Does GYF handle Nordic visa assistance for Kolkata clients?', 'answer' => 'Yes, we provide complete Schengen visa documentation support for all Nordic countries. For Kolkata clients, we prepare all required documents and guide agents through the VFS application process.'],
                    ['question' => 'Are there Scandinavia cultural tour packages for Kolkata art lovers?', 'answer' => 'Yes, our Cultural Nordic tour includes visits to the National Museum of Denmark, Vasa Museum in Stockholm, Munch Museum in Oslo, Design Museum Helsinki, and Viking Ship Museum. We can customize cultural itineraries based on specific interests.'],
                    ['question' => 'What is included in GYF Scandinavia B2B packages for Kolkata agents?', 'answer' => 'Our standard B2B packages include accommodation, daily breakfast, airport transfers, inter-city transportation, English-speaking guides, and key attraction entries. Optional add-ons include Northern Lights excursions, fjord cruises, and special dining experiences.'],
                ],
            ],

            'scandinavia-b2b-dmc-in-hyderabad' => [
                'city_specific_content' => "Hyderabad's rapidly growing outbound travel market is showing increased interest in Scandinavian destinations. Tech companies in HITEC City and Gachibowli are driving demand for Nordic incentive trips, while affluent families in Jubilee Hills and Banjara Hills seek exclusive Scandinavian holiday experiences.\n\nGYF Holidays provides Hyderabad travel agents with comprehensive Scandinavian B2B DMC services including destination expertise, competitive pricing, and on-ground support across all Nordic countries. Our dedicated Hyderabad territory manager ensures local agents receive personalized attention and quick response times.\n\nHyderabad's new direct international routes and improved European hub connections have made Scandinavian travel more accessible than ever for the city's travellers. GYF Holidays packages are optimized for the best Hyderabad departure routings.",
                'seo_content' => "GYF Holidays offers Hyderabad agents specialized Scandinavian packages covering Northern Lights tours, Nordic capital city breaks, Norway fjord expeditions, Finnish Lapland adventures, and Icelandic natural wonders.\n\nOur Hyderabad-focused Scandinavian promotions include early booking discounts for peak Northern Lights season, IT company group packages, premium honeymoon collections, and festival-season special offers aligned with Hyderabad's key travel booking periods.\n\nWe provide Hyderabad agents with comprehensive selling tools including Scandinavia destination guides, visual presentations, client-facing brochures, and social media content to help promote Nordic tours effectively in the Hyderabad market.",
                'faqs' => [
                    ['question' => 'Why should Hyderabad agents choose GYF for Scandinavia tours?', 'answer' => 'GYF Holidays offers Hyderabad agents competitive B2B rates, dedicated territory manager support, comprehensive Nordic destination coverage, 24/7 on-ground support, and proven expertise in handling Indian travellers across Scandinavian countries.'],
                    ['question' => 'What Nordic corporate packages are available for Hyderabad IT companies?', 'answer' => 'We offer Nordic tech innovation tours, Scandinavian team-building packages, Arctic adventure corporate retreats, and Nordic capital MICE packages designed for Hyderabad IT and pharma companies.'],
                    ['question' => 'How does the Northern Lights booking work for Hyderabad clients?', 'answer' => 'We offer Northern Lights packages from September to March. Hyderabad clients can choose between Finland, Norway, Sweden, or Iceland for their Aurora experience. Packages include multiple viewing attempts and alternative activities.'],
                    ['question' => 'Does GYF offer Scandinavian cruise packages for Hyderabad clients?', 'answer' => 'Yes, we offer various Nordic cruise options including Norwegian fjord cruises, Baltic Sea cruises covering multiple Scandinavian capitals, Arctic expedition cruises, and Hurtigruten coastal voyage packages.'],
                    ['question' => 'What is the typical cost range for Scandinavia tours from Hyderabad?', 'answer' => 'Scandinavian tour costs vary by season, destination, and accommodation level. Budget Nordic city breaks start at competitive per-person rates, while premium Northern Lights and Arctic experiences are priced higher. Contact us for detailed B2B pricing.'],
                ],
            ],

            // =====================================================
            // SPECIAL PAGES
            // =====================================================

            'europe-b2b-travel-dmc-in-nagpur' => [
                'city_specific_content' => "Nagpur, the Orange City and the geographical center of India, is an emerging market for European outbound travel. Travel agents in Nagpur are recognizing the growing demand for European tour packages among the city's rising middle class and business community. GYF Holidays provides Nagpur agents with reliable B2B DMC services for European destinations.\n\nNagpur's strategic location in Central India and improving air connectivity make it a key catchment area for European travel demand. The city's business community, particularly those in trade and manufacturing, frequently travels to Europe for business and combines it with leisure extensions.\n\nGYF Holidays offers Nagpur travel agents the same level of service and competitive pricing available to agents in metro cities, ensuring Central India's travel trade can compete effectively in the European tour segment.",
                'seo_content' => "As an emerging market, Nagpur offers significant growth potential for European tour sales. GYF Holidays supports Nagpur agents with comprehensive product training, marketing support, and competitive B2B pricing to help them build their European portfolio.\n\nOur popular packages for the Nagpur market include the Classic Europe tour covering multiple countries over 7-10 nights, London-Paris short breaks, Swiss family holidays, and budget Eastern Europe tours at wholesale B2B rates.\n\nWe provide Nagpur agents with remote support through video training sessions, WhatsApp business communication, and email quotation services, ensuring seamless B2B operations.",
                'faqs' => [
                    ['question' => 'Does GYF Holidays serve travel agents in Nagpur?', 'answer' => 'Yes, GYF Holidays actively serves travel agents in Nagpur and throughout Central India. We provide the same competitive B2B rates, comprehensive European packages, and dedicated support available to agents in major metro cities.'],
                    ['question' => 'What European packages are suitable for Nagpur clients?', 'answer' => 'Popular choices for Nagpur clients include budget-friendly Classic Europe tours, London-Paris city breaks, Swiss family holidays, and group European tours. We also offer premium packages for the growing affluent segment in Nagpur.'],
                    ['question' => 'How can Nagpur travel agents communicate with GYF Holidays?', 'answer' => 'Nagpur agents can reach us via WhatsApp, email, phone, or video calls. We provide remote product training through video sessions and maintain responsive communication channels for quotations, bookings, and support.'],
                    ['question' => 'Does GYF help with European visa for Nagpur clients?', 'answer' => 'Yes, we provide complete Schengen visa documentation support. Since Nagpur clients typically apply through the Mumbai or Delhi VFS centers, we prepare all documents and guide agents through the application process.'],
                ],
            ],

            'europe-b2b-travel-dmc-in-maharashtra' => [
                'city_specific_content' => "Maharashtra, India's most industrialized state and home to Mumbai, Pune, Nagpur, Nashik, and Aurangabad, represents one of the largest European outbound travel markets in India. GYF Holidays serves as a comprehensive B2B DMC partner for travel agents across the entire state of Maharashtra.\n\nMaharashtra's diverse economy spanning financial services in Mumbai, IT in Pune, manufacturing in Nagpur, and agriculture in Nashik generates varied European travel demand. Corporate incentive trips, family holidays, honeymoon packages, and senior citizen group tours all contribute to a robust outbound market.\n\nWith multiple international airports in Mumbai, Pune, and Nagpur, Maharashtra travellers have convenient access to European destinations. GYF Holidays optimizes packages for departures from any Maharashtra gateway, ensuring competitive pricing and efficient routing.",
                'seo_content' => "GYF Holidays offers Maharashtra-wide B2B DMC services covering every major city in the state. Our regional approach ensures travel agents in smaller cities like Nashik, Aurangabad, Solapur, and Kolhapur receive the same quality service and competitive rates as those in Mumbai and Pune.\n\nWe understand Maharashtra's diverse travel preferences from luxury European holidays for Mumbai's elite to value-for-money group tours for agents in Tier-2 cities. Our tiered package structure accommodates all budget segments across the state.\n\nMaharashtra agents benefit from our state-specific promotions during key booking periods including Diwali, Christmas, summer holidays, and long weekends, helping them maximize European tour sales throughout the year.",
                'faqs' => [
                    ['question' => 'Does GYF Holidays cover all cities in Maharashtra?', 'answer' => 'Yes, we serve travel agents across Maharashtra including Mumbai, Pune, Nagpur, Nashik, Aurangabad, Solapur, Kolhapur, Sangli, Satara, and all other cities. Our statewide B2B network ensures consistent service and pricing.'],
                    ['question' => 'What are the most popular Europe destinations for Maharashtra travellers?', 'answer' => 'Maharashtra travellers favour Switzerland, France, Italy, UK, Netherlands, and Spain. The Classic Europe multi-country tour remains the most popular, followed by London-Paris combos and Swiss family packages.'],
                    ['question' => 'How does GYF support travel agents in Maharashtra Tier-2 cities?', 'answer' => 'We provide remote support through video training, WhatsApp communication, email quotations, and marketing material distribution. Agents in Tier-2 cities receive the same B2B rates and product access as metro agents.'],
                    ['question' => 'Does GYF offer seasonal Europe packages for Maharashtra agents?', 'answer' => 'Yes, we offer seasonal promotions aligned with Maharashtra travel patterns including summer holiday packages, Diwali season Europe tours, Christmas and New Year European experiences, and long weekend short European breaks.'],
                    ['question' => 'What airports in Maharashtra connect to Europe?', 'answer' => 'Mumbai offers the most direct European connections including flights to London, Paris, Frankfurt, and Amsterdam. Pune and Nagpur connect through Mumbai or Delhi. GYF Holidays optimizes routing from any Maharashtra departure point.'],
                ],
            ],

            'europe-b2b-dmc-in-pune' => [
                'city_specific_content' => "Pune, India's Oxford of the East and a major IT hub, is a thriving market for European tour packages. Travel agents in Pune serve a diverse clientele including IT professionals, automotive industry executives, students, and affluent families all with growing interest in European travel.\n\nPune's automotive and manufacturing industries have strong European connections, generating regular business travel to Germany, Italy, and France. GYF Holidays helps Pune travel agents convert these business travellers into leisure European tourists with attractive add-on packages and family extensions.\n\nWith Pune International Airport expanding its connectivity and Mumbai airport just a few hours away, Pune travellers have excellent access to European destinations. GYF Holidays offers packages optimized for both Pune and Mumbai departures, giving agents flexibility in routing.",
                'seo_content' => "GYF Holidays supports Pune travel agents with comprehensive European DMC services tailored to the local market. Our Pune-specific offerings include automotive industry European tours visiting car plants in Germany and Italy, IT company incentive packages, educational European tours for Pune's student community, and premium family holiday packages.\n\nPune agents appreciate our competitive pricing that accounts for the city's value-conscious market, along with our premium options for the growing affluent segment in areas like Koregaon Park, Kalyani Nagar, and Baner.\n\nWe organize quarterly product seminars for Pune travel agents at city hotels, covering our latest European offerings and seasonal promotions.",
                'faqs' => [
                    ['question' => 'What European packages are popular with Pune clients?', 'answer' => 'Pune clients prefer Switzerland family tours, London-Paris city breaks, Classic Europe multi-country tours, and automotive industry tours to Germany and Italy. Educational European tours for students and IT company incentive trips are also very popular.'],
                    ['question' => 'Does GYF offer packages departing from Pune airport?', 'answer' => 'Yes, we offer packages from both Pune and Mumbai airports. For Pune departures, we optimize connections through Gulf hubs or Delhi. For better direct European connectivity, we can arrange Mumbai departures with Pune-Mumbai transfers included.'],
                    ['question' => 'How does GYF support Pune IT companies for European trips?', 'answer' => 'We offer comprehensive MICE solutions for Pune IT companies including team-building European packages, conference attendance support, incentive trip planning, and corporate offsite arrangements across European destinations.'],
                    ['question' => 'What B2B benefits does GYF offer Pune travel agents?', 'answer' => 'Pune agents get competitive net rates, flexible payment terms, dedicated support, product training sessions, marketing materials, and seasonal promotional offers. We also offer co-branded marketing support for local promotion.'],
                    ['question' => 'Can GYF customize Europe school and college tours from Pune?', 'answer' => 'Yes, we specialize in educational European tours including visits to universities, museums, historical sites, and cultural landmarks. We handle all logistics including student group visas, supervised accommodation, and educational itineraries.'],
                ],
            ],

            'uk-b2b-travel-dmc-in-mumbai' => [
                'city_specific_content' => "The United Kingdom remains one of the most sought-after destinations for Mumbai travellers, driven by strong historical ties, business connections, and the enduring appeal of London, Scotland, and the English countryside. GYF Holidays is Mumbai's trusted B2B DMC partner for comprehensive UK tour packages.\n\nMumbai's direct flight connectivity to London with multiple daily flights from BOM to LHR and LGW makes UK travel particularly convenient. Our packages leverage this connectivity to offer competitive pricing and flexible departure options for Mumbai agents.\n\nMumbai clients travelling to the UK range from business travellers extending their London trips to families visiting relatives, honeymooners seeking Scottish Highland romance, and groups exploring England's heritage sites. GYF Holidays provides tailored packages for each segment at competitive B2B rates.",
                'seo_content' => "GYF Holidays offers Mumbai travel agents the most comprehensive UK B2B DMC services covering England, Scotland, Wales, and Northern Ireland. Our UK packages range from classic London city breaks to extensive Great Britain tours covering multiple regions.\n\nOur most popular UK packages for Mumbai agents include the 5-night London Explorer, 7-night London to Edinburgh, 10-night Complete Great Britain, Harry Potter themed family tours, Scottish Highlands adventure, and UK-Ireland combination packages.\n\nWe also provide specialized UK services including airport fast-track arrangements at Heathrow, private London transfers, pre-booked attraction tickets, and premium West End theatre bookings that help Mumbai agents offer superior UK experiences.",
                'faqs' => [
                    ['question' => 'What UK tour packages does GYF offer Mumbai travel agents?', 'answer' => 'We offer comprehensive UK packages including London city breaks, London-Edinburgh tours, Complete Great Britain tours, Harry Potter themed packages, Scottish Highlands adventures, UK-Ireland combinations, and business trip leisure extensions at competitive B2B rates.'],
                    ['question' => 'How does the UK visa process work for Mumbai clients?', 'answer' => 'UK requires a separate visa not covered by Schengen. GYF Holidays provides complete UK visa documentation support including invitation letters, hotel bookings, itinerary, and financial documentation guidance. Mumbai clients apply at the VFS UK Visa Centre in Mumbai.'],
                    ['question' => 'What makes GYF the best UK B2B DMC for Mumbai?', 'answer' => 'GYF Holidays offers extensive UK ground handling, competitive B2B rates, comprehensive destination coverage across England, Scotland, Wales, and Ireland, premium add-ons including fast-track and theatre tickets, and 24/7 on-ground support.'],
                    ['question' => 'Does GYF offer UK-Ireland combination packages from Mumbai?', 'answer' => 'Yes, our UK-Ireland combo packages typically cover London, Edinburgh, Dublin, and Belfast over 10-14 nights, including the scenic Irish countryside. Ferry and budget flight options between UK and Ireland are included.'],
                    ['question' => 'Can GYF arrange premium London experiences for Mumbai VIP clients?', 'answer' => 'Absolutely. Our premium London services include luxury airport transfers, private guided tours of Buckingham Palace and Westminster, VIP West End theatre packages, fine dining reservations, luxury shopping assistance at Harrods, and exclusive access experiences.'],
                    ['question' => 'What are the most popular UK attractions for Mumbai tourists?', 'answer' => 'Mumbai tourists most commonly visit London Eye, Tower of London, Buckingham Palace, Big Ben, British Museum, Stonehenge, Edinburgh Castle, Scottish Highlands, Harry Potter Studios, and Oxford and Cambridge. Our packages cover all major attractions.'],
                ],
            ],
        ];
    }
}
